# Action to setup a custom Tcl for building and testing Tcl packages
# See README.md

name: 'Setup Tcl'
description: "Sets up a specific version of Tcl for building extensions"
author: "Ashok P. Nadkarni"
inputs:
  tcl-tag:
    description: "Tag of Tcl repository branch"
    required: true
  target-arch:
    description: "Architecture - x86 or x64. Only used on Windows"
    required: false
    default: 'x64'
  toolchain:
    description: "Toolchain - mingw64 or vc. Only used on Windows"
    required: false
    default: 'vc'

runs:
  using: 'composite'
  steps:

    - name: Set Tcl path for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "TCLDIR=${{ runner.temp }}/tcl/${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
        echo "TCLSUBDIR=${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs" >> $env:GITHUB_ENV

    - name: Set Tcl path for non-Windows
      if: runner.os != 'Windows'
      shell: bash
      run: |
        env
        echo "TCLDIR=${{ runner.temp }}/tcl/${{ inputs.tcl-tag }}" >> $GITHUB_ENV
        echo "TCLSUBDIR=${{ inputs.tcl-tag }}" >> $GITHUB_ENV
        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs" >> $GITHUB_ENV

    - name: Cache Tcl build
      id: tcl-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TCLDIR }}
        key: ${{ runner.os }}-${{ env.ImageOS }}-tcl-${{ env.TCLSUBDIR }}

    - name: Checkout Tcl
      if: steps.tcl-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: tcltk/tcl
        ref: ${{ inputs.tcl-tag }}
        path: tcl-${{ inputs.tcl-tag }}

    - name: Build Tcl on Windows with nmake
      if: runner.os == 'Windows' && inputs.toolchain == 'vc' && steps.tcl-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ inputs.tcl-tag }}/win
      shell: cmd
      run: |
        nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }}
        nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} install

    - name: Build Tcl on Windows with MingW64
      if: runner.os == 'Windows' && inputs.toolchain == 'mingw64' && steps.tcl-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ inputs.tcl-tag }}/win
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        ../configure --prefix=${{ env.TCLDIR }} || (cat config.log && exit 1)
        make -s
        make install

    - name: Build Tcl on non-Windows
      if: runner.os != 'Windows' && steps.tcl-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ inputs.tcl-tag }}/unix
      shell: bash
      run: |
        mkdir build
        cd build
        ../configure --prefix=${{ env.TCLDIR }} || (cat config.log && exit 1)
        make -s
        make install

